version: "0.1"

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      - ./db:/docker-entrypoint-initdb.d:r
    ports:
    - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin_data:/var/lib/pgadmin:rw
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on: 
      - db

volumes:
  postgres_data:
  pgadmin_data: