--
-- PostgreSQL database dump
--

-- Dumped from database version 12.12
-- Dumped by pg_dump version 12.17

-- Started on 2023-12-25 18:33:26 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3057 (class 1262 OID 16384)
-- Name: booking_api_test; Type: DATABASE; Schema: -; Owner: booking_api_test
--

ALTER DATABASE booking_api_test OWNER TO booking_api_test;

\connect booking_api_test

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: booking_api_test
--

ALTER SCHEMA public OWNER TO booking_api_test;

--
-- TOC entry 3058 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: booking_api_test
--

COMMENT ON SCHEMA public IS 'standard public schema';

-- Role: booking_api_user
-- DROP ROLE IF EXISTS booking_api_user;

CREATE ROLE booking_api_user WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD 'md5604a7b5450c1edc2849ad457a4014af2';

GRANT booking_api_test TO booking_api_user WITH ADMIN OPTION;

COMMENT ON ROLE booking_api_user IS 'API Service Account';

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 208 (class 1259 OID 16415)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."AspNetRoleClaims" (
                                           "Id" integer NOT NULL,
                                           "RoleId" text NOT NULL,
                                           "ClaimType" text,
                                           "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO booking_api_test;

--
-- TOC entry 207 (class 1259 OID 16413)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: booking_api_test
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 203 (class 1259 OID 16390)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."AspNetRoles" (
                                      "Id" text NOT NULL,
                                      "Name" character varying(256),
                                      "NormalizedName" character varying(256),
                                      "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO booking_api_test;

--
-- TOC entry 210 (class 1259 OID 16430)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."AspNetUserClaims" (
                                           "Id" integer NOT NULL,
                                           "UserId" text NOT NULL,
                                           "ClaimType" text,
                                           "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO booking_api_test;

--
-- TOC entry 209 (class 1259 OID 16428)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: booking_api_test
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 211 (class 1259 OID 16443)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."AspNetUserLogins" (
                                           "LoginProvider" text NOT NULL,
                                           "ProviderKey" text NOT NULL,
                                           "ProviderDisplayName" text,
                                           "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO booking_api_test;

--
-- TOC entry 212 (class 1259 OID 16456)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."AspNetUserRoles" (
                                          "UserId" text NOT NULL,
                                          "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO booking_api_test;

--
-- TOC entry 213 (class 1259 OID 16474)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."AspNetUserTokens" (
                                           "UserId" text NOT NULL,
                                           "LoginProvider" text NOT NULL,
                                           "Name" text NOT NULL,
                                           "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO booking_api_test;

--
-- TOC entry 204 (class 1259 OID 16398)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."AspNetUsers" (
                                      "Id" text NOT NULL,
                                      "FirstName" text NOT NULL,
                                      "LastName" text NOT NULL,
                                      "BirthDate" timestamp with time zone NOT NULL,
                                      "UserName" character varying(256),
                                      "NormalizedUserName" character varying(256),
                                      "Email" character varying(256),
                                      "NormalizedEmail" character varying(256),
                                      "EmailConfirmed" boolean NOT NULL,
                                      "PasswordHash" text,
                                      "SecurityStamp" text,
                                      "ConcurrencyStamp" text,
                                      "PhoneNumber" text,
                                      "PhoneNumberConfirmed" boolean NOT NULL,
                                      "TwoFactorEnabled" boolean NOT NULL,
                                      "LockoutEnd" timestamp with time zone,
                                      "LockoutEnabled" boolean NOT NULL,
                                      "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO booking_api_test;

--
-- TOC entry 215 (class 1259 OID 16489)
-- Name: Reservations; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."Reservations" (
                                       "Id" integer NOT NULL,
                                       "StartDate" timestamp with time zone NOT NULL,
                                       "EndDate" timestamp with time zone NOT NULL,
                                       "ApplicationUserId" text NOT NULL,
                                       "RoomId" integer NOT NULL,
                                       "Description" text,
                                       "CreatedAt" timestamp with time zone NOT NULL,
                                       "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Reservations" OWNER TO booking_api_test;

--
-- TOC entry 214 (class 1259 OID 16487)
-- Name: Reservations_Id_seq; Type: SEQUENCE; Schema: public; Owner: booking_api_test
--

ALTER TABLE public."Reservations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reservations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 206 (class 1259 OID 16408)
-- Name: Rooms; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."Rooms" (
                                "Id" integer NOT NULL,
                                "Number" integer NOT NULL,
                                "Status" integer NOT NULL,
                                "Type" integer NOT NULL,
                                "Capacity" integer NOT NULL,
                                "CreatedAt" timestamp with time zone NOT NULL,
                                "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Rooms" OWNER TO booking_api_test;

--
-- TOC entry 205 (class 1259 OID 16406)
-- Name: Rooms_Id_seq; Type: SEQUENCE; Schema: public; Owner: booking_api_test
--

ALTER TABLE public."Rooms" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Rooms_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 202 (class 1259 OID 16385)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: booking_api_test
--

CREATE TABLE public."__EFMigrationsHistory" (
                                                "MigrationId" character varying(150) NOT NULL,
                                                "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO booking_api_test;

--
-- TOC entry 2902 (class 2606 OID 16422)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 2892 (class 2606 OID 16397)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 2905 (class 2606 OID 16437)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 2908 (class 2606 OID 16450)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 2911 (class 2606 OID 16463)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 2913 (class 2606 OID 16481)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 2896 (class 2606 OID 16405)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 2917 (class 2606 OID 16496)
-- Name: Reservations PK_Reservations; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id");


--
-- TOC entry 2899 (class 2606 OID 16412)
-- Name: Rooms PK_Rooms; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id");


--
-- TOC entry 2890 (class 2606 OID 16389)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2894 (class 1259 OID 16512)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 2900 (class 1259 OID 16507)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 2903 (class 1259 OID 16509)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 2906 (class 1259 OID 16510)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 2909 (class 1259 OID 16511)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 2914 (class 1259 OID 16514)
-- Name: IX_Reservations_ApplicationUserId; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE INDEX "IX_Reservations_ApplicationUserId" ON public."Reservations" USING btree ("ApplicationUserId");


--
-- TOC entry 2915 (class 1259 OID 16515)
-- Name: IX_Reservations_RoomId; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE INDEX "IX_Reservations_RoomId" ON public."Reservations" USING btree ("RoomId");


--
-- TOC entry 2893 (class 1259 OID 16508)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 2897 (class 1259 OID 16513)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: booking_api_test
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 2918 (class 2606 OID 16423)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 2919 (class 2606 OID 16438)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2920 (class 2606 OID 16451)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2921 (class 2606 OID 16464)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 2922 (class 2606 OID 16469)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2923 (class 2606 OID 16482)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2924 (class 2606 OID 16497)
-- Name: Reservations FK_Reservations_AspNetUsers_ApplicationUserId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "FK_Reservations_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 2925 (class 2606 OID 16502)
-- Name: Reservations FK_Reservations_Rooms_RoomId; Type: FK CONSTRAINT; Schema: public; Owner: booking_api_test
--

ALTER TABLE ONLY public."Reservations"
    ADD CONSTRAINT "FK_Reservations_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES public."Rooms"("Id") ON DELETE CASCADE;


-- PROCEDURE: public.getavailablerooms(date, date)

-- DROP PROCEDURE IF EXISTS public.getavailablerooms(date, date);

CREATE OR REPLACE FUNCTION public.getavailablerooms(
    in startdate date,
    in enddate date)
    RETURNS setof public."Rooms"
    LANGUAGE 'sql'
AS $BODY$
SELECT * FROM public."Rooms" WHERE "Status" = 1 AND "Id" NOT IN (
    SELECT "RoomId" FROM public."Reservations" WHERE "EndDate" >= startDate AND "StartDate" <= endDate
);
$BODY$;

ALTER FUNCTION public.getavailablerooms(date, date)
    OWNER TO booking_api_user;


-- Completed on 2023-12-25 18:33:26 UTC

--
-- PostgreSQL database dump complete
--

